---
- name: Display vault variables
  hosts: webservers
  gather_facts: no
  tasks: 
    - name: Show app database password
      debug:
       msg: "Database pssword is : {{ app_db_password }}"
    - name: Show API key
      debug:
       msg: "API key is : {{ app_api_key }}"